version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: backend.Dockerfile
    ports:
      - "8000:8080"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/mydatabase
      - NODE_OPTIONS=--openssl-legacy-provider
    networks:
      - mynetwork

  frontend:
    build:
      context: ./frontend
      dockerfile: frontend.Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://backend:8080
    networks:
      - mynetwork

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - mynetwork

volumes:
  pgdata:

networks:
  mynetwork:

